[UPUP-1039]: add base navigation module part 1

diff --git a/project.yml b/project.yml
--- a/project.yml
+++ b/project.yml
@@ -101,13 +101,25 @@ targets:
       Release: Source/Configs/release.xcconfig
     preBuildScripts:
       - script: |
-                export PATH="$PATH:/opt/homebrew/bin"
+            export PATH="$HOME/.mint/bin:/opt/homebrew/bin:$PATH"
+            expected_swiflint_version="0.58.2"
 
-                if which swiftlint >/dev/null; then
-                  swiftlint --config .swiftlint.yml
-                else
-                  echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
-                fi
+            echo "Доступные пакеты минта:"
+            mint list
+    
+            if (mint list | grep "$expected_swiflint_version"); then
+                echo "🍀 На машине есть нужная версия линта: ${expected_swiflint_version}"
+                mint install realm/SwiftLint@"$expected_swiflint_version"
+    
+                echo "🍀 Mint переключил версию линта"
+                mint list
+    
+                swiftlint --config .swiftlint.yml
+            else
+                echo "error: 🧨 На машине нет нужной версии линта: ${expected_swiflint_version}"
+                echo "warning: ⚙️ Запустите в терминале команду: mint install realm/SwiftLint@"$expected_swiflint_version""
+                exit 1
+            fi
         name: SwiftLint
         basedOnDependencyAnalysis: false
       - script: |
